In [1]:
from transformers import TFBertForSequenceClassification,BertTokenizer

In [2]:
model = TFBertForSequenceClassification.from_pretrained("model")

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [3]:
tokenizer = BertTokenizer.from_pretrained('tokenizer')

In [4]:
import transformers

In [5]:
transformers.__version__

'4.9.2'

In [6]:
from transformers import pipeline

In [7]:
pipe = pipeline(model=model,tokenizer=tokenizer,task='sentiment-analysis')

In [8]:
pipe('bla')

[{'label': "SEMOULES ET CEREALES D'ACCOMPAGNEMENT",
  'score': 0.4372882843017578}]

In [9]:
import transformers
transformers.__version__

'4.9.2'

In [10]:
model.config.id2label

{0: 'CHEWING GUMS',
 1: 'CONFISERIES DE CHOCOLAT',
 2: 'BONBONS, SUCETTES ET CONFISERIE DE SUCRE',
 3: 'BEERS',
 4: 'WHISKY',
 5: 'BISCUITS SECS',
 6: 'BARRES CEREALIERES',
 7: 'FRUITS SECS',
 8: 'CONFITURES',
 9: "GATEAUX, ROULES, PAINS D'EPICES ET NONNETTES",
 10: 'GOUTERS',
 11: 'CEREALES',
 12: 'BISCUITS SALES',
 13: 'MOUCHOIRS EN PAPIER',
 14: 'PATES A TARTINER',
 15: 'FRESH DESSERTS',
 16: 'APRES SHAMPOOINGS ET SOINS',
 17: 'SHAMPOOINGS',
 18: 'NON DAIRY DRINKS AND CREAMS',
 19: 'MIELS',
 20: 'COOKIES',
 21: 'EXTRUDES ET TUILES',
 22: 'COFFRET DE TOILETTE',
 23: 'SAVONS DE TOILETTE ET PAINS DERMATOLOGIQUES',
 24: 'CREMES DE MARRONS',
 25: 'COMPOTES APPERTISEES ET FRAICHES',
 26: 'RHUMS',
 27: 'AIDE A LA PATISSERIE',
 28: 'VIENNOISERIES',
 29: 'CHANGES ET COUCHES CULOTTES',
 30: 'BISCUITS PATISSIERS',
 31: 'BISCUITS CHOCOLAT ET FRUITS',
 32: 'PRODUITS DEPILATOIRES',
 33: 'HYGIENE BUCCALE ET BAINS DE BOUCHE',
 34: 'EPILATEURS, LUMIERE PULSEE ETC',
 35: 'TOASTS GALETTES ET CRACKERS'

In [11]:
import numpy as np
prediction=model.predict(tokenizer(['bio auchan bio muesli crales croustillantes quinoa chocolat',"gums","hello"],padding=True, truncation=True, return_tensors="tf").data)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [14]:
prediction.logits

array([[ 0.2619929 ,  3.8977263 ,  1.0166389 , ..., -0.79528075,
        -1.6742209 , -0.9255146 ],
       [ 7.804173  ,  3.7603357 ,  9.011575  , ..., -2.1714008 ,
        -0.1209379 , -2.8579834 ],
       [ 2.1395533 ,  2.9372764 ,  1.812624  , ...,  0.39393282,
        -0.14284448, -5.082911  ]], dtype=float32)

In [16]:
import tensorflow as tf 
print(tf.math.softmax(prediction.logits))
prediction = tf.math.softmax(prediction.logits)

tf.Tensor(
[[1.4001304e-06 5.3106476e-05 2.9778798e-06 ... 4.8640794e-07
  2.0196755e-07 4.2701276e-07]
 [1.2520224e-01 2.1948051e-03 4.1877431e-01 ... 5.8247242e-06
  4.5266821e-05 2.9315433e-06]
 [5.6002429e-03 1.2435222e-02 4.0385295e-03 ... 9.7744761e-04
  5.7144440e-04 4.0881823e-06]], shape=(3, 334), dtype=float32)


In [30]:
prediction.shape

TensorShape([3, 334])

In [33]:
idx

array([11,  2, 71], dtype=int64)

In [26]:
idx = np.argmax(prediction,axis=-1)

In [28]:
list(idx)

[11, 2, 71]

In [29]:
idx = np.argmax(prediction,axis=-1)
list(map(lambda x: (model.config.id2label.get(x)),list(idx)))

['CEREALES',
 'BONBONS, SUCETTES ET CONFISERIE DE SUCRE',
 'TABLETTES DE CHOCOLAT']

In [37]:
prediction.numpy()

array([[1.4001304e-06, 5.3106476e-05, 2.9778798e-06, ..., 4.8640794e-07,
        2.0196755e-07, 4.2701276e-07],
       [1.2520224e-01, 2.1948051e-03, 4.1877431e-01, ..., 5.8247242e-06,
        4.5266821e-05, 2.9315433e-06],
       [5.6002429e-03, 1.2435222e-02, 4.0385295e-03, ..., 9.7744761e-04,
        5.7144440e-04, 4.0881823e-06]], dtype=float32)

In [43]:
list(np.max(prediction,axis=-1))

[0.9971578, 0.4187743, 0.11852857]

In [24]:
import pandas as pd

In [25]:
pd.DataFrame({"Class":list(map(lambda x: (model.config.id2label.get(x)),idx[0])),"Score":list(np.max(prediction,axis=-1)[0])})

TypeError: 'numpy.int64' object is not iterable

In [76]:
prediction

<tf.Tensor: shape=(1, 1, 334), dtype=float32, numpy=
array([[[1.40013572e-06, 5.31067308e-05, 2.97789120e-06, 1.72611877e-07,
         4.17271212e-06, 2.56511089e-06, 1.00337400e-03, 1.60297793e-06,
         1.22551291e-05, 9.09924347e-06, 6.82554219e-06, 9.97157812e-01,
         3.34873675e-06, 6.93357691e-08, 2.37421027e-05, 1.01389669e-04,
         5.08803350e-06, 1.01747328e-05, 2.12247614e-05, 1.10937290e-05,
         2.86111990e-05, 9.01179956e-05, 2.57025903e-07, 2.03519086e-08,
         4.59502508e-06, 2.46775471e-05, 3.17965873e-06, 7.85899101e-06,
         8.49754633e-06, 7.75418266e-06, 1.79308645e-05, 4.47820639e-05,
         4.35537856e-07, 7.70479360e-08, 3.30892718e-08, 1.13148526e-05,
         7.09622867e-08, 2.81259759e-06, 3.38015282e-09, 3.11414823e-07,
         1.92094269e-08, 1.35392853e-04, 1.96493588e-07, 1.88346760e-07,
         1.84234898e-06, 9.66779226e-08, 9.40130292e-07, 2.88971933e-06,
         3.81834226e-08, 4.30969704e-09, 1.21122996e-08, 2.12364625e-07

In [32]:
dict(tokenizer(['hello']))

{'input_ids': [[101, 7592, 102]],
 'token_type_ids': [[0, 0, 0]],
 'attention_mask': [[1, 1, 1]]}

In [89]:
pipe1= pipeline(model="model",tokenizer = Bertokenizer.from_pretrained('tokenizer'),task='sentiment-analysis')

NameError: name 'Bertokenizer' is not defined

In [87]:
tokenizer.config

AttributeError: 'BertTokenizer' object has no attribute 'config'

In [41]:
tokenizer

PreTrainedTokenizer(name_or_path='tokenizer', vocab_size=30522, model_max_len=512, is_fast=False, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [42]:

tokenizer(['bio auchan bio muesli crales croustillantes quinoa chocolat',"gums","hello"],padding=True, truncation=True, return_tensors="tf").data

{'input_ids': <tf.Tensor: shape=(3, 21), dtype=int32, numpy=
 array([[  101, 16012,  8740, 14856, 16012, 14163,  2229,  3669, 13675,
         23266, 13675,  3560, 28345, 24985, 21864,  3630,  2050, 16480,
         26289,  2102,   102],
        [  101, 16031,  2015,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [  101,  7592,   102,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]])>,
 'token_type_ids': <tf.Tensor: shape=(3, 21), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>,
 'attention_mask': <tf.Tensor: shape=(3, 21), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [43]:
import pandas as pd

In [44]:
pd.Series(tokenizer(['bio auchan bio muesli crales croustillantes quinoa chocolat',"gums","hello"],padding=True, truncation=True, return_tensors="tf").data)

input_ids         ((tf.Tensor(101, shape=(), dtype=int32), tf.Te...
token_type_ids    ((tf.Tensor(0, shape=(), dtype=int32), tf.Tens...
attention_mask    ((tf.Tensor(1, shape=(), dtype=int32), tf.Tens...
dtype: object

In [44]:
import joblib

In [45]:
id2label = model.config.id2label

In [46]:
label2id = model.config.label2id

In [47]:
joblib.dump(id2label,"id2label.json")

['id2label.json']

In [48]:
joblib.load("id2label.json")

{0: 'CHEWING GUMS',
 1: 'CONFISERIES DE CHOCOLAT',
 2: 'BONBONS, SUCETTES ET CONFISERIE DE SUCRE',
 3: 'BEERS',
 4: 'WHISKY',
 5: 'BISCUITS SECS',
 6: 'BARRES CEREALIERES',
 7: 'FRUITS SECS',
 8: 'CONFITURES',
 9: "GATEAUX, ROULES, PAINS D'EPICES ET NONNETTES",
 10: 'GOUTERS',
 11: 'CEREALES',
 12: 'BISCUITS SALES',
 13: 'MOUCHOIRS EN PAPIER',
 14: 'PATES A TARTINER',
 15: 'FRESH DESSERTS',
 16: 'APRES SHAMPOOINGS ET SOINS',
 17: 'SHAMPOOINGS',
 18: 'NON DAIRY DRINKS AND CREAMS',
 19: 'MIELS',
 20: 'COOKIES',
 21: 'EXTRUDES ET TUILES',
 22: 'COFFRET DE TOILETTE',
 23: 'SAVONS DE TOILETTE ET PAINS DERMATOLOGIQUES',
 24: 'CREMES DE MARRONS',
 25: 'COMPOTES APPERTISEES ET FRAICHES',
 26: 'RHUMS',
 27: 'AIDE A LA PATISSERIE',
 28: 'VIENNOISERIES',
 29: 'CHANGES ET COUCHES CULOTTES',
 30: 'BISCUITS PATISSIERS',
 31: 'BISCUITS CHOCOLAT ET FRUITS',
 32: 'PRODUITS DEPILATOIRES',
 33: 'HYGIENE BUCCALE ET BAINS DE BOUCHE',
 34: 'EPILATEURS, LUMIERE PULSEE ETC',
 35: 'TOASTS GALETTES ET CRACKERS'

In [49]:
joblib.dump(label2id,"label2id.json")

['label2id.json']